remote_theme: pages-themes/architect@v0.2.0
plugins:
- jemoji
- jekyll-remote-theme

title: Xintong Wu
description: Xintong Wu's Github Page of STATS201: Introduction to Machine Learning for Social Science Final Project
